---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirect
  namespace: default
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(?:card|cal)dav"
    replacement: "https://${1}/remote.php/dav"

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: default
spec:
  chart: nextcloud
  repo: https://nextcloud.github.io/helm/
  version: 6.5.2
  targetNamespace: default
  valuesContent: |-
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-nextcloud-redirect@kubernetescrd
        homer.service.name: Media
        homer.item.rank: "2"
        homer.item.logo: "https://github.com/nextcloud/server/raw/0450e47f8dda26d19a0a252ddd5a117fddfa6885/core/img/logo/logo.png"
        homer.item.type: "Nextcloud"
      hosts:
        - host: nextcloud.{{ .Values.fqdn }}
          paths:
            - path: /
      tls:
        - secretName: {{ .Values.fqdn }}-tls
          hosts:
            - nextcloud.{{ .Values.fqdn }}
    nodeSelector:
      # Schedule only on NAS nodes
      nas: "true"
    resources:
      requests:
        memory: 128Mi
        cpu: 250m
      limits:
        memory: 8Gi
        cpu: 4000m
    nextcloud:
      host: nextcloud.{{ .Values.fqdn }}
      trustedDomains:
        - nextcloud.{{ .Values.fqdn }}
      extraEnv:
        - name: TRUSTED_PROXIES
          value: "10.43.0.0/16"
        - name: REDIS_HOST
          value: "redis-master"
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp
              key: hostname
        - name: SMTP_NAME
          valueFrom:
            secretKeyRef:
              name: smtp
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp
              key: password
        - name: SMTP_SECURE
          value: "tls"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_AUTHTYPE
          value: "login"
        - name: MAIL_FROM_ADDRESS
          value: "nextcloud"
        - name: MAIL_DOMAIN
          value: "{{ .Values.fqdn }}"
      extraVolumeMounts:
        - name: app
          mountPath: /var/www/html
        - name: data
          mountPath: /var/www/html/data
      extraVolumes:
        - name: app
          hostPath:
            path: /storage/nextcloud/app
        - name: data
          hostPath:
            path: /storage/nextcloud/data
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgres
      host: postgresql
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: postgres.postgresql.credentials.postgresql.acid.zalan.do
        usernameKey: username
        passwordKey: password
    redis:
      auth:
        enabled: true
        existingSecret: redis
        existingSecretPasswordKey: redis-password
    cronjob:
      enabled: true
    livenessProbe:
      failureThreshold: 10
    readinessProbe:
      failureThreshold: 10
