# code: language=ansible
---
- name: Apply folder manifests
  become: true
  run_once: true
  block:
    - name: Set facts
      ansible.builtin.set_fact:
        aggregate_path: "/tmp/{{ folder_name }}.yml"
        manifests_folder: "{{ kubernetes_project_location }}/{{ folder_name }}"
        domain_dc: "dc={{ fqdn.split(\".\")[0] | lower }},dc={{ fqdn.split(\".\")[1] | lower }}"

    - name: Generate aggregate manifest file
      ansible.builtin.shell: "set -o pipefail && cat {{ manifests_folder }}/*.yml | env DOMAIN_NAME={{ fqdn }} DOMAIN_DC={{ domain_dc }} envsubst '$DOMAIN_NAME $DOMAIN_DC' > {{ aggregate_path }}"
      args:
        executable: /usr/bin/bash
      delegate_to: localhost
      run_once: true
      become: false
      changed_when: false

    - name: Copy aggregate file to remote
      ansible.posix.synchronize:
        src: "{{ aggregate_path }}"
        dest: "{{ aggregate_path }}"

    - name: Apply aggregate manifest
      ansible.builtin.command: "kubectl apply -f {{ aggregate_path }}"
      changed_when: false

- name: Wait for manifests to install
  ansible.builtin.command: "kubectl wait --for=condition=complete jobs --all --all-namespaces --timeout=2m"
  changed_when: false
  become: true
  run_once: true
