---
apiVersion: v1
kind: Secret
metadata:
  name: authelia
  namespace: default
type: Opaque
# stringData:
#   jwt_secret: "some_secret"
#   storage_encryption_key: "some_key"
#   session_encryption_key: "some_key"
#   ldap_password: "somepass"  # manually create a user called "authelia" in the "lldap_password_manager" group via lldap

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia
  namespace: default
spec:
  chart: authelia
  repo: https://charts.authelia.com
  version: 0.9.8
  targetNamespace: default
  valuesContent: |-
    ingress:
      enabled: true
      rulesOverride:
        - host: authelia.${DOMAIN_NAME}
          path: '/'
      certManager: false
      rewriteTarget: false
      tls:
        enabled: true
        secret: '${DOMAIN_NAME}-tls'
      traefikCRD:
        enabled: true
        disableIngressRoute: true
        middlewares:
          forwardAuth:
            nameOverride: 'authelia'
            address: http://authelia:9091/api/verify?rd=https://authelia.${DOMAIN_NAME}/'
            trustForwardHeader: true
            authResponseHeaders:
            - 'Remote-User'
            - 'Remote-Name'
            - 'Remote-Email'
            - 'Remote-Groups'
    pod:
      kind: 'Deployment'
      replicas: 2
      resources:
        requests:
          cpu: '0.25'
          memory: '50Mi'
        limits:
          cpu: '2.00'
          memory: '250Mi'
      env:
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia
              key: jwt_secret
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: authelia
              key: storage_encryption_key
        - name: AUTHELIA_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia
              key: session_encryption_key
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authelia
              key: ldap_password
        - name: AUTHELIA_SESSION_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis_password
        - name: AUTHELIA_NOTIFIER_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp
              key: password
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.postgresql.credentials.postgresql.acid.zalan.do
              key: password
    configMap:
      log:
        level: 'info'
        format: 'text'
        file_path: ''
      default_2fa_method: 'totp'
      theme: 'dark'
      identity_validation:
        reset_password:
          jwt_lifespan: '5 minutes'
          jwt_algorithm: 'HS256'
          secret:
            disabled: true
        elevated_session:
          code_lifespan: '5 minutes'
          elevation_lifespan: '10 minutes'
          characters: 8
          require_second_factor: false
          skip_second_factor: false
      totp:
        issuer: 'Authelia'
        skew: 1
        secret_size: 64
        algorithm: 'SHA512'
        digits: 6
        period: 30
        allowed_algorithms:
          - 'SHA512'
        allowed_digits:
          - 6
        allowed_periods:
          - 30
      webauthn:
        timeout: '60 seconds'
        display_name: 'Authelia'
        attestation_conveyance_preference: 'indirect'
        user_verification: 'preferred'
      ntp:
        address: 'udp://time.cloudflare.com:123'
        version: 4
        max_desync: '3 seconds'
        disable_startup_check: false
        disable_failure: false
      authentication_backend:
        refresh_interval: '5 minutes'
        ldap:
          enabled: true
          implementation: 'custom'
          address: 'ldap://lldap'
          timeout: '5s'
          start_tls: false
          base_dn: '${DOMAIN_DC}'
          additional_users_dn: ou=people
          users_filter: (&({username_attribute}={input})(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          user: uid=authelia,ou=people,${DOMAIN_DC}
          permit_referrals: false
          attributes:
            display_name: displayName
            username: uid
            group_name: cn
            mail: mail
          password:
            disabled: true
      password_policy:
        zxcvbn:
          enabled: true
          min_score: 3
      access_control:
        default_policy: 'deny'
        networks: []
        rules: []
      session:
        name: 'authelia_session'
        same_site: 'lax'
        expiration: '1 hour'
        inactivity: '5 minutes'
        remember_me: '1 month'
        encryption_key:
          disabled: true
        cookies:
          - subdomain: authelia
            domain: ${DOMAIN_NAME}
        redis:
          enabled: true
          deploy: false
          enabledSecret: true
          host: 'redis'
          port: 6379
          password:
            disabled: true
      storage:
        encryption_key:
          disabled: true
        postgres:
          enabled: true
          deploy: false
          address: 'tcp://postgresql:5432'
          timeout: '5 seconds'
          database: 'authelia'
          schema: 'public'
          username: 'postgres'
          password:
            disabled: true
      notifier:
        smtp:
          enabled: true
          enabledSecret: false
          address: 'submission://email-smtp.us-east-1.amazonaws.com:587'
          timeout: '5 seconds'
          sender: 'Authelia <authelia@${DOMAIN_NAME}>'
          subject: '[Authelia] {title}'
          ## This address is used during the startup check to verify the email configuration is correct.
          ## It's not important what it is except if your email server only allows local delivery.
          startup_check_address: 'test@authelia.com'
          username: 'AKIA2UC3CZ4IUGTQWQ4L'
          password:
            disabled: true
    secret:
      disabled: true
      existingSecret: authelia
