---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgresql
  namespace: default
spec:
  teamId: arch-anes
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
  numberOfInstances: 3
  volume:
    size: 10Gi
    storageClass: local-path-retain
  preparedDatabases:
    authelia: {}
    bazarr: {}
    gotify: {}
    immich:
      extensions:
        vector: public
    kubeclarity: {}
    lldap: {}
    miniflux: {}
    n8n: {}
    nextcloud: {}
    pgadmin4: {}
    prowlarr_log: {}
    prowlarr_main: {}
    radarr_log: {}
    radarr_main: {}
    readarr_cache: {}
    readarr_log: {}
    readarr_main: {}
    sonarr_log: {}
    sonarr_main: {}
    speedtest_tracker: {}
